version: '3.8'

services:
  pictrs-safety:
    image: ghcr.io/db0/pictrs-safety:latest
    hostname: "pictrs-safety"
    ports:
      - "14051:14051"    
    expose:
      - '14051'
    
    user: 991:991

    # See .env_template for description of each variable
    environment:
      - USE_SQLITE=1
      - FEDIVERSE_SAFETY_WORKER_AUTH=abcd1312
      - FEDIVERSE_SAFETY_IMGDIR=/tmp/images
      - secret_key=abcdefggjhsarfvcxnewqwedq

    restart: unless-stopped
